# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_teacher_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image_path',
            field=models.FileField(blank=True, upload_to='/images/teachers'),
        ),
    ]
