# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20170825_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='images/teachers'),
        ),
    ]
