# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-30 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publish-time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='update-time')),
            ],
        ),
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100, verbose_name='\u5e74\u7ea7\u7b49\u7ea7')),
                ('slug', models.CharField(max_length=100, verbose_name='\u7b49\u7ea7\u5730\u5740')),
                ('intro', models.CharField(max_length=100, verbose_name='\u7b49\u7ea7\u4ecb\u7ecd')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSubjectMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_grade', models.CharField(max_length=20)),
                ('tab_grade_dsc', models.CharField(max_length=20)),
                ('tab_subject', models.CharField(max_length=20)),
                ('tab_subject_dsc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u540d\u79f0')),
                ('slug', models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u5730\u5740')),
                ('intro', models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u4ecb\u7ecd')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tec_title', models.CharField(max_length=100)),
                ('tec_age', models.IntegerField(default=0)),
                ('tec_area', models.CharField(max_length=50)),
                ('tec_info', models.CharField(max_length=200)),
                ('tec_limit_price', models.FloatField(default=0)),
                ('tec_max_price', models.FloatField(default=0)),
                ('tec_evaluation_num', models.IntegerField(default=0)),
                ('tec_other_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='gradeinfo',
            name='subject',
            field=models.ManyToManyField(to='homepage.SubjectInfo', verbose_name='\u79d1\u76ee\u5217\u8868'),
        ),
    ]
