# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100, verbose_name='\u5e74\u7ea7\u7b49\u7ea7')),
                ('slug', models.CharField(max_length=100, verbose_name='\u7b49\u7ea7\u5730\u5740')),
                ('intro', models.CharField(max_length=100, verbose_name='\u7b49\u7ea7\u4ecb\u7ecd')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u540d\u79f0')),
                ('slug', models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u5730\u5740')),
                ('intro', models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u4ecb\u7ecd')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('S', 'Sec'), ('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('area', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
                ('limit_price', models.FloatField(default=0)),
                ('max_price', models.FloatField(default=0)),
                ('evaluation_num', models.IntegerField(default=0)),
                ('other_info', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publish-time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='update-time')),
                ('skill', models.ManyToManyField(to='homepage.GradeSubject', verbose_name='\u6280\u80fd')),
                ('skill2', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='homepage.Subject', verbose_name='\u6280\u80fd2')),
            ],
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='subject',
            field=models.ManyToManyField(to='homepage.Subject', verbose_name='\u79d1\u76ee\u5217\u8868'),
        ),
    ]
