# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skill',
            field=models.ManyToManyField(to='homepage.GradeSubject', verbose_name='grade_subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skill2',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='homepage.Subject', verbose_name='subject'),
        ),
    ]
