# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubjectMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_grade', models.CharField(max_length=20)),
                ('tab_grade_dsc', models.CharField(max_length=20)),
                ('tab_subject', models.CharField(max_length=20)),
                ('tab_subject_dsc', models.CharField(max_length=20)),
            ],
        ),
    ]
