# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170815_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image_path',
            field=models.FileField(blank=True, upload_to='./upload/images/teachers'),
        ),
    ]
