# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_grade_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='intro',
            field=models.CharField(max_length=100, verbose_name='\u7b49\u7ea7\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.CharField(max_length=100, verbose_name='\u5e74\u7ea7\u7b49\u7ea7'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='\u7b49\u7ea7\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='intro',
            field=models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100, verbose_name='\u79d1\u76ee\u540d\u79f0'),
        ),
    ]
