# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170822_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image_path',
            field=models.FileField(blank=True, upload_to='./static/upload/images/teachers'),
        ),
    ]
