# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20170822_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='./images/teachers'),
        ),
    ]
