# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-14 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usermane',
            new_name='username',
        ),
    ]
